language: java
# get us on the new container based builds, we're not using any fancyness
sudo: false
jdk:
- openjdk7
before_cache:
  - du -h -d 2 $HOME/.m2/
  - find $HOME/.m2 -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.m2
install:
  - mkdir installers && curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > installers/jpm4j.jar
  - java -jar installers/jpm4j.jar -u init && rm -r installers && export PATH=$PATH:$HOME/jpm/bin
  - jpm install com.codacy:codacy-coverage-reporter:assembly
script:
- mvn clean install -f ./rest-api-commons-core/pom.xml
- mvn clean install -f ./rest-api-commons-test/pom.xml
- mvn clean install -f ./rest-api-back-end/rest-api-parent/pom.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codacy-coverage-reporter -l Java -r ./rest-api-back-end/rest-api-webapp/target/site/cobertura/coverage.xml
email : false